[system]
subsystems = ["video", "events", "geometry"]

[window]
title = "test"
width = 800
height = 640
flags = ["input-grabbed", "fulscreen-laptop"]

[renderer]
flags = ["accelerated", "reduced-speed"]
